### ISSUE TITLE
VTK package 

### ISSUE THREAD

**Issue by Ale909** [fbottarel/manip-env-visu#3]
Vtk is not found, in order to use the library you need to add 
find_package(VTK 8.2 REQUIRED)
in the CMakeLists file

**Comment by fbottarel** [comment]
Fixed in 75a05587ceb67e4938097103cd1b490ea2cd94f7.
Now the library is installed as a cmake target and transitive dependencies are taken care of automatically.
You still need to provide paths to libraries that have been installed in custom paths, e.g. `VTK_DIR`.
